# Generated by Django 4.0 on 2021-12-28 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=50, null=True)),
                ('rider_Number', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riders_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('customer_contact', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerEntry.riders')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='MultipleEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact', models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('Rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerEntry.riders')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomerEntry.riders_log')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
