# Generated by Django 4.0 on 2022-01-04 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleentries',
            name='customer_contact',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
