# Generated by Django 4.0 on 2022-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerEntry', '0002_alter_multipleentries_customer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders_log',
            name='count',
            field=models.ManyToManyField(to='CustomerEntry.MultipleEntries'),
        ),
    ]
